-- speed up
require("impatient")
require("toggle")
require("refactoring").setup()
require("null")
require("glow").setup()
require("lualine_setup")
require("luasnip.loaders.from_vscode").lazy_load()
require("luasnip.loaders.from_vscode").lazy_load({ paths = { "/Users/jingdizhu/.config/nvim/my_snippets" } })
require("luasnip.loaders.from_lua").load({ paths = "~/.config/nvim/my_snippets/lua/" })
require("lsp_config")
require("go_test")
require("tele")
require("telescope").load_extension("frecency")
require("git")
require("term")
require("syntex")
require("session")
require("indent")
require("nvim-autopairs").setup({})
require("dap-go").setup()
require("dap_set")
require("nerdtree")
require("fastmind")
require("go").setup()
require("txtobj")
require("input_method")
require("start")
