vim.keymap.set("n", "<C-d>", "<C-d>zz")
vim.keymap.set("n", "<C-u>", "<C-u>zz")
vim.keymap.set("n", "n ", "nzzzv")
vim.keymap.set("n", "N ", "Nzzzv")
vim.keymap.set("n", "<silent> <C-Left> :vertical resize", "+5<CR>")
vim.keymap.set("n", "<silent> <C-Right> :vertical resize", "-5<CR>")
vim.keymap.set("n", "<silent> <C-Up> :resize", "+5<CR>")
vim.keymap.set("n", "<silent> <C-Down> :resize", "-5<CR>")
vim.keymap.set("n", "0", "^")
vim.keymap.set("n", "<Leader>q", ":wq<CR>")
vim.keymap.set("n", "<Leader>gs", ":Git<CR>")
vim.keymap.set("n", "<Leader>gb :Git", "blame<CR>")
vim.keymap.set("n", "<Leader>t", ":NERDTreeToggle<CR>")
vim.keymap.set("n", "<Leader>s", ":sp<CR>")
vim.keymap.set("n", "<Leader>ss :source", "~/.config/nvim/init.vim<CR>")
vim.keymap.set("n", "<Leader>v", ":vsp<CR>")
vim.keymap.set("n", "<Leader>w", ":w<CR>")
vim.keymap.set("n", " <Leader>r", ":GoRename<CR>")
vim.keymap.set("n", "<Leader>1", ":1ToggleTerm<CR>")
vim.keymap.set("n", "<Leader>2", ":2ToggleTerm<CR>")
vim.keymap.set("n", "<Leader>3", ":3ToggleTerm<CR>")
vim.keymap.set("n", "<Leader>4", ":4ToggleTerm<CR>")
vim.keymap.set("n", "<Leader>5", ":5ToggleTerm<CR>")
vim.keymap.set("n", "<Leader>6", ":6ToggleTerm<CR>")
vim.keymap.set("n", "<Leader>7", ":7ToggleTerm<CR>")
vim.keymap.set("n", "<Leader>8", ":8ToggleTerm<CR>")
vim.keymap.set("n", "<Leader>9", ":9ToggleTerm<CR>")
vim.keymap.set("n", "<Leader>rt", ":GoRunTestFunc<CR>")
vim.keymap.set("n", "<Leader>rf", ":GoRunTestFile<CR>")
vim.keymap.set("n", "<Leader>de :lua", 'require"dap".toggle_breakpoint()<CR>')
vim.keymap.set("n", "<Leader>ut", ":UndotreeToggle<CR>")
